# GitHub Secret Scanning Configuration
# This file tells GitHub to exclude certain paths from secret scanning

paths-ignore:
  - '**/*.example'
  - '**/.env.example'
  - '**/.env.*.example'
  - '**/README.md'
  - '**/DEPLOYMENT.md'
  - '**/*.md'
